### ISSUE TITLE
Global config for ssh jobs

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc-ssh#35]
Issue #16 discusses problems caused by DVC initiating too many sessions when communicating with SSH remotes.

This can be configured _per remote per project_ with
```
dvc remote modify <remote_name> jobs <limit>
```
The number of sessions is 4 x `jobs`, so setting `jobs` to `2` will keep us under the default value of 10 for `MaxSessions` in ` /etc/ssh/sshd_config`. 

It would be helpful if a default value for `jobs` could be set globally.

**Comment by pmrowla** [comment]
This is already possible using the `--global` or `--system` flags (i.e. `dvc remote modify --global <remote_name> ...`). The config setting will still be per remote, but can be applied to all DVC repo's that use the given remote name for either yourself (with `--global`) or for anyone using your machine (with `--system`).

See the docs for `dvc config` for details https://dvc.org/doc/command-reference/config#description

**Comment by johnyaku** [comment]
Thanks @pmrowla
